---
title: "ML1"
output: pdf_document
date: "2024-01-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Setup
```{r cars cache=TRUE}

#Install and import libraries.
if (!require("quantmod")) install.packages("quantmod")
if (!require("PortfolioAnalytics")) install.packages("PortfolioAnalytics")
if (!require("PerformanceAnalytics")) install.packages("PerformanceAnalytics")
if (!require("ggplot2")) install.packages("ggplot2")
if (!require("ROI")) install.packages("ROI")
if (!require("ROI.plugin.quadprog")) install.packages("ROI.plugin.quadprog")
if (!require("fPortfolio")) install.packages("fPortfolio")
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("lubridate")) install.packages("lubridate")
if (!require("corrplot")) install.packages("corrplot")
if (!require("dbscan")) install.packages("dbscan")
if (!require("dplyr")) install.packages("dplyr")
if (!require("GGally")) install.packages("GGally")
if (!require("tm")) install.packages("tm")
if (!require("tidytext")) install.packages("tidytext")
if (!require("wordcloud")) install.packages("wordcloud")


library(readr,quietly = T)
library(quantmod, quietly = T)
library(PortfolioAnalytics, quietly = T)
library(PerformanceAnalytics, quietly = T)
library(ggplot2, quietly = T)
library(ROI, quietly = T)
library(ROI.plugin.quadprog, quietly = T)
library(fPortfolio, quietly = T)
library(tidyverse, quietly = T)
library(lubridate, quietly = T)
library(corrplot, quietly = T)
library(dbscan)
library(dplyr)
library(GGally)
library(NLP)
library(RColorBrewer)
library(tm)
library(wordcloud)
library(tidytext)


# DATA LOAD
# without column-types shown
data_motor <- read_csv("data/motor_data14-2018.csv", show_col_types = FALSE)


str(data_motor)
```



```{r cars cache=TRUE}

#DATA PREP
data_motor$SEX<-as.factor(data_motor$SEX)
#data_motor$INSR_BEGIN<- as.Date(data_motor$INSR_BEGIN, format = "%m/%d/%Y")
#data_motor$INSR_END
 
 
#data_motor$INSR_BEGIN <- as.Date(data_motor$INSR_BEGIN, format = "%d-%b-%y")
#
## Funktion, um das Datum zu parsen, abh채ngig vom Format
#data_motor$INSR_BEGIN <- ifelse(grepl("-", data_motor$INSR_BEGIN) & grepl("[A-Za-z]", data_motor$INSR_BEGIN),
#                                as.Date(data_motor$INSR_BEGIN, format = "%d-%b-%y"),  # Format f체r '09-MAY-18'
#                                as.Date(data_motor$INSR_BEGIN, format = "%Y-%m-%d"))  # Format f체r '2015-11-28'
#
# Den modifizierten Datensatz anzeigen
#data_motor$INSR_BEGIN <- as.Date(data_motor$INSR_BEGIN)  # Sicherstellen, dass
 
 
data_motor$OBJECT_ID<-as.factor(data_motor$OBJECT_ID)
data_motor$MAKE<-as.factor(data_motor$MAKE)
data_motor$USAGE<-as.factor(data_motor$USAGE)
data_motor$TYPE_VEHICLE<-as.factor(data_motor$TYPE_VEHICLE)
data_motor$CARRYING_CAPACITY<-as.numeric(data_motor$CARRYING_CAPACITY)
data_motor <- data_motor[, !names(data_motor) %in% "EFFECTIVE_YR"]
 
# Entfernen der Zeilen, wo 'make' nicht mit einem Buchstaben beginnt
data_motor <- data_motor[grepl("^[A-Za-z]", data_motor$MAKE), ] 
data_motor$CLAIM_PAID[is.na(data_motor$CLAIM_PAID)] <- 0
data_motor$CARRYING_CAPACITY[is.na(data_motor$CARRYING_CAPACITY)] <- 0
table(data_motor$TYPE_VEHICLE)
 
 
# LUCA
# Drop rows with NA values in specific columns
data_motor <- data_motor[!is.na(data_motor$PREMIUM) & !is.na(data_motor$PROD_YEAR) & !is.na(data_motor$CCM_TON) & !is.na(data_motor$MAKE) & !is.na(data_motor$SEATS_NUM), ]
# Check for the number of missing values in each column
colSums(is.na(data_motor))
# Create a new column to determine if the claim was paid
data_motor$CLAIM <- ifelse(data_motor$CLAIM_PAID == 0, 'NO', 'YES')

# Map the values of the SEX column to a new GENDER column
data_motor$GENDER <- dplyr::recode(data_motor$SEX, `0` = 'Legal Entity', `1` = 'Male', `2` = 'Female')
# Drop the SEX column
data_motor <- data_motor[, !names(data_motor) %in% 'SEX']
 
# Map the values of the INSR_TYPE column to a new TYPE_INSR column
data_motor$TYPE_INSR <- dplyr::recode(data_motor$INSR_TYPE, 
                                      `1201` = 'Private', 
                                      `1202` = 'Commercial', 
                                      `1204` = 'Motor Trade Road Risk')
# Drop the INSR_TYPE column
data_motor <- data_motor[, !names(data_motor) %in% 'INSR_TYPE']
# Count how many zeros are in the INSURED_VALUE column
insured_value_zeros <- sum(data_motor$INSURED_VALUE == 0)
cat('Number of values with zero in insured value:', insured_value_zeros, '\n')
 
#FIXME to be discussed
# Calculate the median of INSURED_VALUE by TYPE_VEHICLE, MAKE, and PROD_YEAR 
median_insured_value <- ave(data_motor$INSURED_VALUE, data_motor$TYPE_VEHICLE, data_motor$MAKE, data_motor$PROD_YEAR, 
                            FUN = function(x) median(x, na.rm = TRUE))
 
# Replace 0s in INSURED_VALUE with the calculated median
data_motor$INSURED_VALUE[data_motor$INSURED_VALUE == 0] <- median_insured_value[data_motor$INSURED_VALUE == 0]

# Calculate the median of CARRYING_CAPACITY by TYPE_VEHICLE and MAKE
median_carrying_capacity <- ave(data_motor$CARRYING_CAPACITY, data_motor$TYPE_VEHICLE, data_motor$MAKE, 
                                FUN = function(x) median(x, na.rm = TRUE))
# Replace 0s in CARRYING_CAPACITY with the calculated median
data_motor$CARRYING_CAPACITY[data_motor$CARRYING_CAPACITY == 0] <- median_carrying_capacity[data_motor$CARRYING_CAPACITY == 0]


 
# Replace 0s in INSURED_VALUE with the calculated median
data_motor$INSURED_VALUE[data_motor$INSURED_VALUE == 0] <- median_insured_value[data_motor$INSURED_VALUE == 0]
 
 
# Calculate the median of CARRYING_CAPACITY by TYPE_VEHICLE and MAKE
#data_motor$CARRYING_CAPACITY[is.na(data_motor$CARRYING_CAPACITY)] <- 0

median_carrying_capacity <- ave(data_motor$CARRYING_CAPACITY, data_motor$TYPE_VEHICLE, data_motor$MAKE, 
                                FUN = function(x) median(x, na.rm = TRUE))
 
# Replace 0s in CARRYING_CAPACITY with the calculated median
data_motor$CARRYING_CAPACITY[data_motor$CARRYING_CAPACITY == 0] <- median_carrying_capacity[data_motor$CARRYING_CAPACITY == 0]
 
 
# Count how many zeros are in the PREMIUM column
premium_zeros <- sum(data_motor$PREMIUM == 0)
cat('Number of values with zero in premium:', premium_zeros, '\n')
data_motor <- data_motor[data_motor$PREMIUM != 0, ]
# Count how many zeros are in the CARRYING_CAPACITY column
carrying_capacity_zeros <- sum(data_motor$CARRYING_CAPACITY == 0)
cat('Number of values with zero in carrying capacity:', carrying_capacity_zeros, '\n')
# Count how many zeros are in the SEATS_NUM column
seats_num_zeros <- sum(data_motor$SEATS_NUM == 0)
cat('Number of values with zero in number of seats:', seats_num_zeros, '\n')


```



# Models
## Linear Model
```{r Linear-Model}
# TODO
str(data_motor)
summary(data_motor)

 #Premium= gender, insured value, prod_year, seats number, capacity, type vehicle,  cctm_ton, make, usage

# Erstelle das lineare Regressionsmodell mit den erkl채renden Variablen
lm_model <- lm(PREMIUM ~ SEX + INSURED_VALUE + PROD_YEAR + SEATS_NUM + CARRYING_CAPACITY + 
               TYPE_VEHICLE + CCM_TON + MAKE + USAGE, data = data_motor)

# Zusammenfassung des Modells anzeigen
summary(lm_model)


```


## Poisson
```{r Poisson-Model}
# TODO

```


## Binomial
```{r Binomial-Model}
# TODO

```

## Generalised Additive Model (GAM)
```{r GAM}
# TODO

```

## Neural Network
```{r Neural-Network}
# TODO

```


## Support Vector Machine (SVM)
```{r SVM}
# TODO

```


# Conclusion





